### ISSUE TITLE
A few icons not rendering correctly?

### ISSUE THREAD

**Issue by glennrm93** [alexanderschau/react-ionicons#11]
Hi @alexanderschau , we've recently found a couple of small inconsistencies between how a few of the icons are rendered when compared to how they look on the ionic website. I created a super quick example here on codesandbox: https://codesandbox.io/s/festive-lovelace-vq9yqp?file=/src/App.tsx

Here are those three previewed from the ionic website directly:

![image](https://user-images.githubusercontent.com/45487806/215741309-baa2c676-9a99-48d0-89b0-958e3feeb320.png)

![image](https://user-images.githubusercontent.com/45487806/215741416-24372404-9aa8-41af-a82e-f9bad731aa42.png)

![image](https://user-images.githubusercontent.com/45487806/215741529-5c5dacdd-956a-4f98-b964-caa86a6ac3e0.png)

I'm not sure if there are more than this too but those are the three we stumbled across.

It would be awesome if you could take a look to see what might be happening here?

Thanks for your help!

**Comment by abhishekpolampally** [comment]
Hey, this issue still exists. Can you please take a look at this? I will submit a PR when request whenever I get some time.

**Comment by alexanderschau** [comment]
Sorry for the late response. I somehow forgot about this issue. I am very confident that I resolved the bug now, however if it's still not working feel free to reopen. @AvidDesigner thanks for offering your help 💚.

**Comment by glennrm93** [comment]
Hey @alexanderschau , thanks for fixing this! I have updated to v7 and the icons are rendering as expected now :) 

I did notice one small thing however, the type for the `name` property is erroring within my editor:

`Type 'IconList' is not assignable to type '"all icon names"'.`

![image](https://user-images.githubusercontent.com/45487806/226388420-c3c65560-8eaf-4641-83ce-303a1101a5a8.png)

The `IconList` type is a list of all icon names that we use within the project.

**Comment by alexanderschau** [comment]
Hey @glennrm93, turned out to be a simple typing error 🙃. Should be fixed with v7.0.1 :).

**Comment by glennrm93** [comment]
Thanks @alexanderschau , that's perfect now 😄
