### ISSUE TITLE
ReferenceError: module is not defined in ES module scope.

### ISSUE THREAD

**Issue by batmanhit** [alexanderschau/react-ionicons#13]
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/node_modules/@reacticons/ionicons/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

**Comment by batmanhit** [comment]
@alexanderschau I am getting this weird error with `7.0.1`

I am using `next.js` and `typescript`.

**Comment by alexanderschau** [comment]
should be fixed with v7.1.0, otherwise feel free to reopen
