### ISSUE TITLE
New prop request `size`

### ISSUE THREAD

**Issue by batmanhit** [alexanderschau/react-ionicons#4]
@alexanderschau, your package really saved our time but we have a small request.
Is it possible to add `size` prop to the component?

https://ionic.io/ionicons/usage
![image](https://user-images.githubusercontent.com/30376020/152168764-da795165-9146-4292-913f-71cf0b8a4d00.png)

**Comment by alexanderschau** [comment]
First of all, thanks for using this package!
I implemented it right away and the result would look similar to the following:
![](https://user-images.githubusercontent.com/42480227/152187871-8463fa9f-9db1-45fc-8da8-95d64c5d3b88.png)
If this solves your issue I would merge it and you could then use it beginning with the next release.
