### ISSUE TITLE
Using another container element other than a div

### ISSUE THREAD

**Issue by jcvandan** [alexanderschau/react-ionicons#6]
Hey, it would be useful if you could specify a different container element for the svg icon. `<div>` is not a valid child component of `<p>` / `<span>` and many more, meaning HTML will not pass validation checks, and also means react logs warnings about this. An icon is something we would ideally want to use anywhere in our markup without this restriction.

I'm happy to have a go at this and create a PR, but would be useful if you could give me an idea of how difficult (or maybe easy) it might be to do this.

Thanks.

**Comment by alexanderschau** [comment]
Oh, I didn't thought about that.
Please feel free to open a PR replacing the `<div>`. I think a `<span>` would work just fine. You may need to do some smaller CSS changes, but all in all this should be an easy one :smiley:.

**Comment by jcvandan** [comment]
I just tested this out locally and when swapping to a `span`, the `IonIcon` component continues to work as before in our project. I just raised a little PR #7 for the change.

Thanks for the work on the library, it's been very useful for my team.
